spring:
  datasource:
    url: jdbc:postgresql://34.172.161.190:5432/my_database
    username: sd-dev
    password: Tv(=<]]r<HQP0J?]
  flyway:
    locations: "classpath:db/migration"

flyway:
  validate-on-migrate: false
  encoding: UTF8MB4
  out-of-order: true